name: Publish Scheduled Posts

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  publish-scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger publish scheduled endpoint
        run: |
          curl -X GET "${{ secrets.DEPLOY_URL }}/api/publish-scheduled" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          -H "Content-Type: application/json" \
          --fail
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
